export const dummy = [
  {
    id: "1",
    clientId: "CL0001",
    names: "Client Names",
    username: "Username",
    country: "Country Name",
    telephone: "+000000000000",
    status: "Pending",
  },
  {
    id: "2",
    clientId: "CL0002",
    names: "Client Names",
    username: "Username",
    country: "Country Name",
    telephone: "+000000000000",
    status: "Pending",
  },
  {
    id: "3",
    clientId: "CL0003",
    names: "Client Names",
    username: "Username",
    country: "Country Name",
    telephone: "+000000000000",
    status: "Pending",
  },
  {
    id: "4",
    clientId: "CL0004",
    names: "Client Names",
    username: "Username",
    country: "Country Name",
    telephone: "+000000000000",
    status: "Pending",
  },
  {
    id: "5",
    clientId: "CL0005",
    names: "Client Names",
    username: "Username",
    country: "Country Name",
    telephone: "+000000000000",
    status: "Pending",
  },
  {
    id: "6",
    clientId: "CL0006",
    names: "Client Names",
    username: "Username",
    country: "Country Name",
    telephone: "+000000000000",
    status: "Pending",
  },
  {
    id: "7",
    clientId: "CL0007",
    names: "Client Names",
    username: "Username",
    country: "Country Name",
    telephone: "+000000000000",
    status: "Pending",
  },
  {
    id: "8",
    clientId: "CL0008",
    names: "Client Names",
    username: "Username",
    country: "Country Name",
    telephone: "+000000000000",
    status: "Pending",
  },
  {
    id: "9",
    clientId: "CL0009",
    names: "Client Names",
    username: "Username",
    country: "Country Name",
    telephone: "+000000000000",
    status: "Pending",
  },
  {
    id: "10",
    clientId: "CL00010",
    names: "Client Names",
    username: "Username",
    country: "Country Name",
    telephone: "+000000000000",
    status: "Pending",
  },
  {
    id: "11",
    clientId: "CL00011",
    names: "Client Names",
    username: "Username",
    country: "Country Name",
    telephone: "+000000000000",
    status: "Pending",
  },
  {
    id: "12",
    clientId: "CL00012",
    names: "Client Names",
    username: "Username",
    country: "Country Name",
    telephone: "+000000000000",
    status: "Pending",
  },
  {
    id: "13",
    clientId: "CL00013",
    names: "Client Names",
    username: "Username",
    country: "Country Name",
    telephone: "+000000000000",
    status: "Pending",
  },
  {
    id: "14",
    clientId: "CL00014",
    names: "Client Names",
    username: "Username",
    country: "Country Name",
    telephone: "+000000000000",
    status: "Pending",
  },
  {
    id: "15",
    clientId: "CL00015",
    names: "Client Names",
    username: "Username",
    country: "Country Name",
    telephone: "+000000000000",
    status: "Pending",
  },
];
